export {Home} from "./Home"
export {LoginSignUp} from "./LoginSignUp"
export {EmailSent} from "./EmailSent"
export {SuccessOnRegistration} from "./SuccessOnRegistration"
export {SuccessOnPasswordReset} from "./SuccessOnPasswordReset"
export {PageNotFound} from "./PageNotFound"